tap 'caskroom/cask'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'diff-so-fancy'
brew 'git'
brew 'grip'
brew 'hub'
brew 'rcm'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'vim'
brew 'yarn'
brew 'zsh-syntax-highlighting'
cask 'alfred'
cask 'atom'
cask 'google-chrome'
cask 'hyper'
